id: P009309
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20744
  title: མི་ཕམ་འཇམ་དབྱངས་རྣམ་རྒྱལ་རྒྱ་མཚོའི་རྣམ་ཐར་སྙིང་བསྡུས།
  author: ''
  volumes:
    836be33d2e8a4c1993ad1715a6cdd23e:
      image_group_id: I8LS20758
      title: ''
      volume_number: 1
      total_pages: 156
      base_file: v001.txt
