id: IBB94999D
legacy_id: P009309
ocr_import_info:
  bdrc_scan_id: W8LS20744
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T11:38:28'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T13:24:17.624100+00:00'
last_modified: 2022-08-27 21:24:25.221164
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS20744
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW8LS20744
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མི་ཕམ་འཇམ་དབྱངས་རྣམ་རྒྱལ་རྒྱ་མཚོའི་རྣམ་ཐར་སྙིང་བསྡུས།
  author: དིལ་མགོ་མཁྱེན་བརྩེ་བཀྲ་ཤིས་དཔལ་འབྱོར།
statistics:
  ocr_word_mean_confidence_index: 0.9560726512177589
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I8LS20758:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS20758
      total_pages: 156
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS20758.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9560726512177589
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
